CREATE TABLE IF NOT EXISTS contacts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	phone TEXT,
	email TEXT
);

CREATE TABLE IF NOT EXISTS link_queue (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	url TEXT NOT NULL,
	content TEXT,
	last_scrapped DATETIME,
	error TEXT
);
